name: ibyeol_note
description: "Ibyeol-note application"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  flutter_dotenv: ^5.1.0

  flutter_riverpod: ^2.5.1
  retrofit: ^4.4.1
  dio: ^5.7.0

  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  shared_preferences: ^2.3.2
  go_router: ^14.3.0
  intl: ^0.20.1
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  change_app_package_name: ^1.3.0
  freezed: ^2.5.7
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true

  assets:
    - assets/develop.env
    - assets/release.env
    - assets/place_holder.png
    - assets/fonts/

  fonts:
    - family: MinSans
      fonts:
        - asset: assets/fonts/MinSans-Regular.otf
          weight: 400
        - asset: assets/fonts/MinSans-Medium.otf
          weight: 500
    - family: NanumMyeongjo
      fonts:
        - asset: assets/fonts/NanumMyeongjoBold.otf
          weight: 700
    - family: SpoqaHanSansNeo
      fonts:
        - asset: assets/fonts/SpoqaHanSansNeo-Light.otf
          weight: 300
        - asset: assets/fonts/SpoqaHanSansNeo-Regular.otf
          weight: 400
        - asset: assets/fonts/SpoqaHanSansNeo-Medium.otf
          weight: 500
        - asset: assets/fonts/SpoqaHanSansNeo-Bold.otf
          weight: 700
